import json
from typing import List, Dict, Any

# OpenWebUI Tool Definition
# This is a conceptual representation of how the tool would be defined for OpenWebUI.
# In a real implementation, this would be a Python function decorated with @tools.tool or similar.

def query_knowledge_base(query: str, top_k: int = 5, walk_depth: int = 1) -> List[Dict[str, Any]]:
    """
    Query the SensusVault knowledge base for information. 
    Performs a semantic search and expands the context using the graph-aware logic.
    
    Args:
        query: The natural language question or topic to search for.
        top_k: The number of top results to return.
        walk_depth: The depth of the graph-walk to perform for related entities.
        
    Returns:
        A list of relevant notes with their IDs, titles, and content summaries.
    """
    import requests
    
    API_BASE_URL = "http://localhost:8000"
    
    try:
        # In a real scenario, the embedding would be generated by a local model 
        # or an external API (like OpenAI or Ollama) before sending this request.
        # For this tool definition, we assume the 'query' string is processed.
        
        # This is a placeholder for actual embedding logic:
        # embedding = embedding_model.encode(query)
        dummy_embedding = [0.1] * 1536 
        
        response = requests.post(
            f"{API_BASE_URL}/query",
            json={
                "query_text": query,
                "top_k": top_k,
                "walk_depth": walk_depth
            },
            timeout=30
        )
        response.raise_for_status()
        return response.json().get("results", [])
    except Exception as e:
        return [{"error": f"Failed to query knowledge base: {str(e)}"}]

def list_pending_actions() -> List[Dict[str, Any]]:
    """
    List all actions proposed by the Knowledge Agent that are awaiting human approval.
    
    Returns:
        A list of actions with their types, payloads, and IDs.
    """
    import requests
    
    API_BASE_URL = "http://localhost:8000"
    
    try:
        response = requests.get(f"{API_BASE_URL}/actions")
        response.raise_for_status()
        return response.json()
    except Exception as e:
        return [{"error": f"Failed to fetch actions: {str(e)}"}]

def approve_action(action_id: str) -> Dict[str, str]:
    """
    Approve a specific action proposed by the Knowledge Agent.
    
    Args:
        action_id: The unique identifier of the action to approve.
        
    Returns:
        A confirmation message.
    """
    import requests
    
    API_BASE_URL = "http://localhost:8000"
    
    try:
        response = requests.post(f"{API_BASE_URL}/actions/{action_id}/approve")
        response.raise_for_status()
        return {"message": f"Action {action_id} approved successfully."}
    except Exception as e:
        return {"error": f"Failed to approve action {action_id}: {str(e)}"}

def reject_action(action_id: str) -> Dict[str, str]:
    """
    Reject a specific action proposed by the Knowledge Agent.
    
    Args:
        action_id: The unique identifier of the action to reject.
        
    Returns:
        A confirmation message.
    """
    import requests
    
    API_BASE_URL = "http://localhost:8000"
    
    try:
        response = requests.post(f"{API_BASE_URL}/actions/{action_id}/reject")
        response.raise_for_status()
        return {"message": f"Action {action_id} rejected successfully."}
    except Exception as e:
        return {"error": f"Failed to reject action {action_id}: {str(e)}"}

# JSON definition for OpenWebUI (for reference)
# {
#   "name": "SensusVault",
#   "description": "Access your private knowledge base and manage agentic actions.",
#   "tools": [
#     {
#       "name": "query_knowledge_base",
#       "description": "Query the SensusVault knowledge base for information. Performs a semantic search and expands the context using the graph-aware logic.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "query": { "type": "string", "description": "The natural language question or topic to search for." },
#           "top_k": { "type": "integer", "default": 5 },
#           "walk_depth": { "type": "integer", "default": 1 }
#         },
#         "required": ["query"]
#       }
#     },
#     {
#       "name": "list_pending_actions",
#       "description": "List all actions proposed by the Knowledge Agent that are awaiting human approval.",
#       "parameters": {
#         "type": "object",
#         "properties": {}
#       }
#     },
#     {
#       "name": "approve_action",
#       "description": "Approve a specific action proposed by the Knowledge Agent.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "action_id": { "type": "string", "description": "The unique identifier of the action to approve." }
#         },
#         "required": ["action_id"]
#       }
#     },
#     {
#       "name": "reject_action",
#       "description": "Reject a specific action proposed by the Knowledge Agent.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "action_id": { "type": "string", "description": "The unique identifier of the action to reject." }
#         },
#         "required": ["action_id"]
#       }
#     }
#   ]
# }
