import json
from typing import List, Dict, Any

class Tools:
    """
    OpenWebUI Tool Definition
    This is a conceptual representation of how the tool would be defined for OpenWebUI.
    In a real implementation, this would be a Python function decorated with @tools.tool or similar.
    """

import os
import json
from typing import List, Dict, Any

class Tools:
    """
    OpenWebUI Tool Definition
    This is a conceptual representation of how the tool would be defined for OpenWebUI.
    In a real implementation, this would be a Python function decorated with @tools.tool or similar.
    """

    def __init__(self):
        # Change to your APP URL
        self.api_base_url = "http://host.docker.internal:2200"

    def sensusvault_query_knowledge_base(self, query: str, top_k: int = 5, walk_depth: int = 1) -> List[Dict[str, Any]]:
        """
        Query the SensusVault knowledge base for information.
        Performs a semantic search and expands the context using the graph-aware logic.
        
        Args:
            query: The natural language question or topic to search for.
            top_k: The number of top results to return.
            walk_depth: The depth of the graph-walk to perform for related entities.
            
        Returns:
            A list of relevant notes with their IDs, titles, and content summaries.
        """
        import requests
        
        try:
            # In a real scenario, the embedding would be generated by a local model
            # or an external API (like OpenAI or Ollama) before sending this request.
            # For this tool definition, we assume the 'query' string is processed.
            
            # This is a placeholder for actual embedding logic:
            # embedding = embedding_model.encode(query)
            dummy_embedding = [0.1] * 384
            
            response = requests.post(
                f"{self.api_base_url}/query",
                json={
                    "query_text": query,
                    "top_k": top_k,
                    "walk_depth": walk_depth
                },
                timeout=30
            )
            response.raise_for_status()
            return response.json().get("results", [])
        except Exception as e:
            return [{"error": f"Failed to query knowledge base: {str(e)}"}]

    def sensusvault_list_pending_actions(self) -> List[Dict[str, Any]]:
        """
        List all actions proposed by the Knowledge Agent that are awaiting human approval.
        
        Returns:
            A list of actions with their types, payloads, and IDs.
        """
        import requests
        
        try:
            response = requests.get(f"{self.api_base_url}/actions")
            response.raise_for_status()
            return response.json()
        except Exception as e:
            return [{"error": f"Failed to fetch actions: {str(e)}"}]

    def sensusvault_approve_action(self, action_id: str) -> Dict[str, str]:
        """
        Approve a specific action proposed by the Knowledge Agent.
        
        Args:
            action_id: The unique identifier of the action to approve.
            
        Returns:
            A confirmation message.
        """
        import requests
        
        try:
            response = requests.post(f"{self.api_base_url}/actions/{action_id}/approve")
            response.raise_for_status()
            return {"message": f"Action {action_id} approved successfully."}
        except Exception as e:
            return {"error": f"Failed to approve action {action_id}: {str(e)}"}

    def sensusvault_reject_action(self, action_id: str) -> Dict[str, str]:
        """
        Reject a specific action proposed by the Knowledge Agent.
        
        Args:
            action_id: The unique identifier of the action to reject.
            
        Returns:
            A confirmation message.
        """
        import requests
        
        try:
            response = requests.post(f"{self.api_base_url}/actions/{action_id}/reject")
            response.raise_for_status()
            return {"message": f"Action {action_id} rejected successfully."}
        except Exception as e:
            return {"error": f"Failed to reject action {action_id}: {str(e)}"}

    def sensusvault_create_note(self, content: str, title: str, source: str, tags: List[str] = None) -> Dict[str, str]:
        """
        Directly create a new note in the SensusVault database.
        
        Args:
            content: The main content of the note.
            title: The title of the note.
            source: The source of the information.
            tags: Optional list of tags for the note.
            
        Returns:
            A confirmation message with the new note's ID.
        """
        import requests
        
        try:
            response = requests.post(
                f"{self.api_base_url}/notes",
                json={
                    "content": content,
                    "title": title,
                    "source": source,
                    "tags": tags or []
                },
                timeout=30
            )
            response.raise_for_status()
            data = response.json()
            return {"message": "Note created successfully", "id": data.get("id")}
        except Exception as e:
            return {"error": f"Failed to create note: {str(e)}"}

# JSON definition for OpenWebUI (for reference)
# {
#   "name": "SensusVault",
#   "description": "Access your private knowledge base and manage agentic actions.",
#   "tools": [
#     {
#       "name": "sensusvault_query_knowledge_base",
#       "description": "Query the SensusVault knowledge base for information. Performs a semantic search and expands the context using the graph-aware logic.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "query": { "type": "string", "description": "The natural language question or topic to search for." },
#           "top_k": { "type": "integer", "default": 5 },
#           "walk_depth": { "type": "integer", "default": 1 }
#         },
#         "required": ["query"]
#       }
#     },
#     {
#       "name": "sensusvault_list_pending_actions",
#       "description": "List all actions proposed by the Knowledge Agent that are awaiting human approval.",
#       "parameters": {
#         "type": "object",
#         "properties": {}
#       }
#     },
#     {
#       "name": "sensusvault_approve_action",
#       "description": "Approve a specific action proposed by the Knowledge Agent.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "action_id": { "type": "string", "description": "The unique identifier of the action to approve." }
#         },
#         "required": ["action_id"]
#       }
#     },
#     {
#       "name": "sensusvault_reject_action",
#       "description": "Reject a specific action proposed by the Knowledge Agent.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "action_id": { "type": "string", "description": "The unique identifier of the action to reject." }
#         },
#         "required": ["action_id"]
#       }
#     },
#     {
#       "name": "sensusvault_create_note",
#       "description": "Directly create a new note in the SensusVault database.",
#       "parameters": {
#         "type": "object",
#         "properties": {
#           "content": { "type": "string", "description": "The main content of the note." },
#           "title": { "type": "string", "description": "The title of the note." },
#           "source": { "type": "string", "description": "The source of the information." },
#           "tags": { "type": "array", "items": { "type": "string" }, "description": "Optional list of tags for the note." }
#         },
#         "required": ["content", "title", "source"]
#       }
#     }
#   ]
# }
